# Generated by Django 5.1.4 on 2025-03-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokemon_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("types", models.JSONField(default=list)),
                ("sprite_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
