# Generated by Django 5.1.4 on 2025-01-31 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("my_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[
                            ("GENRE", "Genre"),
                            ("ARTIST", "Artist"),
                            ("TRACK", "Track"),
                        ],
                        max_length=10,
                    ),
                ),
                ("preference_value", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="my_users.user",
                    ),
                ),
            ],
        ),
    ]
